CREATE TABLE IF NOT EXISTS user_tokens (
	id SERIAL PRIMARY KEY,
	user_id INTEGER,
	token TEXT UNIQUE,
	expiry TIMESTAMP,
	FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE
);
